### ISSUE TITLE
PSP_LARGE_MEMORY = 1

### ISSUE THREAD

**Issue by VGkav** [173210/snes9xTYL#10]
Shouldn't this be enabled in the makefile ?

**Comment by 173210** [comment]
I don't know.
But it works fine now, and it may disable PSP Fat to launch this emulator.
I don't enable it for now.

**Comment by VGkav** [comment]
http://lukasz.dk/mirror/forums.ps2dev.org/viewtopic798a-2.html?t=10767

Look at that thread from the mirror of the old ps2dev forum. It seems fat psps are unaffected. By the way, do you have a Vita ?

Also, on my slim, the emulator always shows Free RAM: 377kb ... weird. I'm gonna try with that flag enabled to see how much RAM it reports.

**Comment by 173210** [comment]
I don't have a Vita.

It reports how much free in user memory but it can use large memory.

**Comment by 173210** [comment]
It seems to enable malloc to use large memory.
But we don't use malloc to use large memory, so I don't enable the flag.
