### ISSUE TITLE
r27 Freezes when opening a game

### ISSUE THREAD

**Issue by michaeldauria** [173210/snes9xTYL#13]
This happens on both with and without the ME versions. Once snes9xTYL has loaded, choose any game (mine are uncompressed) and it will freeze immediately and the PSP will turn off.

Hardware: PSP-1001
Firmware: 6.60 PRO-C2

**Comment by 173210** [comment]
Do you know the latest version which works with your PSP?

**Comment by michaeldauria** [comment]
I only see r27 available under releases: https://github.com/173210/snes9xTYL/releases

Where can I find older versions?

**Comment by 173210** [comment]
Snes9xTYLmecm(/cm) 0.4.2 Mod - Wololo.net /Downloads - View Download
http://wololo.net/downloads/index.php/download/7904

**Comment by michaeldauria** [comment]
I can't seem to get the mecm version of r26, but the cm version works fine. Once I choose a game i see a progress bar and then it ends up loading the game. On r27, the MemoryStick light goes on and it gets stuck before the progress bar shows up.

**Comment by 173210** [comment]
It seems to have caused an exception.  Well, can you use PSPLink?
https://github.com/173210/psplinkusb/releases

**Comment by michaeldauria** [comment]
I've never used it before and I am on a Mac, I'll see what I can do.

**Comment by michaeldauria** [comment]
So it looks like I am going to have to compile the whole toolchain, which I am willing to do, but I am having some trouble. Can you give me some direction on what I need to install and do to have it work for me?

**Comment by VGkav** [comment]
I think I found a link for mecm r25, check it out:
http://endlessparadigm.com/forum/showthread.php?tid=30248

**Comment by michaeldauria** [comment]
This is no longer an issue as of r28
